//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLicnaDokumentaPasos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGradjanin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGradjanin()
        {
            this.tblPasos = new HashSet<tblPaso>();
        }
    
        public int GradjaninID { get; set; }
        public string Tip { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public int JMBG { get; set; }
        public string Pol { get; set; }
        public Nullable<System.DateTime> DatumIzdavanja { get; set; }
        public Nullable<System.DateTime> DatumRodjenja { get; set; }
        public string MestoRodjenja { get; set; }
        public string DrzavaRodjenja { get; set; }
        public string Prebivaliste { get; set; }
        public string KodDrzave { get; set; }
        public int MaloletnoLice { get; set; }
    
        public virtual tblMaloletnoLouse tblMaloletnoLouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPaso> tblPasos { get; set; }
    }
}
