//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLicnaDokumentaPasos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaloletnoLouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMaloletnoLouse()
        {
            this.tblGradjanins = new HashSet<tblGradjanin>();
            this.tblPasos = new HashSet<tblPaso>();
        }
    
        public int MaloletnoLiceID { get; set; }
        public string UverenjeODrzavljanstvu { get; set; }
        public string IzvodMaticneKnjigeRodjenih { get; set; }
        public string UplaceneNaknade { get; set; }
        public string SaglasnostRoditelja { get; set; }
        public string Fotografija { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGradjanin> tblGradjanins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPaso> tblPasos { get; set; }
    }
}
