//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLicnaDokumentaPasos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGradjanin
    {
        public int GradjaninID { get; set; }
        public string Tip { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public int JMBG { get; set; }
        public string Pol { get; set; }
        public Nullable<System.DateTime> DatumIzdavanja { get; set; }
        public Nullable<System.DateTime> DatumRodjenja { get; set; }
        public string MestoRodjenja { get; set; }
        public string DrzavaRodjenja { get; set; }
        public string Prebivaliste { get; set; }
        public string KodDrzave { get; set; }
        public Nullable<int> MaloletnoLice { get; set; }
        public string Expr1 { get; set; }
        public int Expr2 { get; set; }
        public string Expr3 { get; set; }
        public string Expr4 { get; set; }
        public int Expr5 { get; set; }
        public string Expr6 { get; set; }
        public Nullable<System.DateTime> Expr7 { get; set; }
        public Nullable<System.DateTime> Expr8 { get; set; }
        public string Expr9 { get; set; }
        public string Expr10 { get; set; }
        public string Expr11 { get; set; }
        public string Expr12 { get; set; }
        public Nullable<int> Expr13 { get; set; }
        public int MaloletnoLiceID { get; set; }
        public string UverenjeODrzavljanstvu { get; set; }
        public string IzvodMaticneKnjigeRodjenih { get; set; }
        public string UplaceneNaknade { get; set; }
        public string SaglasnostRoditelja { get; set; }
        public string Fotografija { get; set; }
        public int Expr14 { get; set; }
        public string Expr15 { get; set; }
        public string Expr16 { get; set; }
        public string Expr17 { get; set; }
        public string Expr18 { get; set; }
        public string Expr19 { get; set; }
    }
}
