//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLicnaDokumentaPasos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwInformacijeOPasosu
    {
        public int InformacijeOPasosuID { get; set; }
        public string Email { get; set; }
        public int Telefon { get; set; }
        public int IzdavanjePasosa { get; set; }
        public int ProduzetakPasosa { get; set; }
        public int Expr1 { get; set; }
        public string Expr2 { get; set; }
        public int Expr3 { get; set; }
        public int Expr4 { get; set; }
        public int Expr5 { get; set; }
        public int IzdavanjePasosaID { get; set; }
        public string LicnaKarta { get; set; }
        public string Fotografija { get; set; }
        public string IzvodMaticneKnjigeRodjenih { get; set; }
        public string UverenjeODrzavljanstvu { get; set; }
        public string UplataZaPasos { get; set; }
        public int Expr6 { get; set; }
        public string Expr7 { get; set; }
        public string Expr8 { get; set; }
        public string Expr9 { get; set; }
        public string Expr10 { get; set; }
        public string Expr11 { get; set; }
        public int Expr13 { get; set; }
        public string Expr12 { get; set; }
        public string Expr14 { get; set; }
    }
}
