//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLicnaDokumentaPasos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwIzdavanjePasosa
    {
        public int IzdavanjePasosaID { get; set; }
        public string LicnaKarta { get; set; }
        public string Fotografija { get; set; }
        public string IzvodMaticneKnjigeRodjenih { get; set; }
        public string UverenjeODrzavljanstvu { get; set; }
        public string UplataZaPasos { get; set; }
        public int Expr1 { get; set; }
        public string Expr2 { get; set; }
        public string Expr3 { get; set; }
        public string Expr4 { get; set; }
        public string Expr5 { get; set; }
        public string Expr6 { get; set; }
    }
}
