//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLicnaDokumentaPasos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwKorisnik
    {
        public int KorsinikID { get; set; }
        public string Email { get; set; }
        public string Lozinka { get; set; }
        public int Pasos { get; set; }
        public int Expr1 { get; set; }
        public string Expr2 { get; set; }
        public string Expr3 { get; set; }
        public int Expr4 { get; set; }
        public int Expr5 { get; set; }
        public string Expr6 { get; set; }
        public string Expr7 { get; set; }
        public int Expr8 { get; set; }
        public int Expr10 { get; set; }
        public int Expr11 { get; set; }
        public int Expr12 { get; set; }
        public int Expr13 { get; set; }
        public int Expr14 { get; set; }
    }
}
