//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLicnaDokumentaPasos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPaso
    {
        public int Expr1 { get; set; }
        public string Expr2 { get; set; }
        public string Expr3 { get; set; }
        public int Expr4 { get; set; }
        public string Expr5 { get; set; }
        public int Expr6 { get; set; }
        public int Expr7 { get; set; }
        public int PasosID { get; set; }
        public string IzdajePU { get; set; }
        public string Drzava { get; set; }
        public int Telefon { get; set; }
        public string Email { get; set; }
        public int InformacijeOPasosu { get; set; }
        public int Uplata { get; set; }
        public int Gradjanin { get; set; }
        public int MaloletnoLice { get; set; }
        public int IzgubljenPasos { get; set; }
        public int Expr8 { get; set; }
        public int Expr9 { get; set; }
        public int Expr10 { get; set; }
        public int GradjaninID { get; set; }
        public string Tip { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public int JMBG { get; set; }
        public string Pol { get; set; }
        public Nullable<System.DateTime> DatumIzdavanja { get; set; }
        public Nullable<System.DateTime> DatumRodjenja { get; set; }
        public string MestoRodjenja { get; set; }
        public string DrzavaRodjenja { get; set; }
        public string Prebivaliste { get; set; }
        public string KodDrzave { get; set; }
        public int IzgubljenPasosID { get; set; }
        public string PrijavaNestanka { get; set; }
        public string NevazecaIsprava { get; set; }
        public string VadiNoviPasos { get; set; }
        public int Expr11 { get; set; }
        public string Expr12 { get; set; }
        public string Expr13 { get; set; }
        public string Expr14 { get; set; }
        public int Expr15 { get; set; }
        public int UplataID { get; set; }
        public string ObrzacPutneIsprave { get; set; }
        public string AdministrativnaTaksa { get; set; }
        public string Expr16 { get; set; }
        public string Expr17 { get; set; }
        public int InformacijeOPasosuID { get; set; }
        public int IzdavanjePasosa { get; set; }
        public int ProduzetakPasosa { get; set; }
        public int Expr18 { get; set; }
        public string Expr19 { get; set; }
        public string Expr20 { get; set; }
        public string Expr21 { get; set; }
        public string Expr22 { get; set; }
        public string Expr23 { get; set; }
        public int MaloletnoLiceID { get; set; }
        public string UverenjeODrzavljanstvu { get; set; }
        public string IzvodMaticneKnjigeRodjenih { get; set; }
        public string UplaceneNaknade { get; set; }
        public string SaglasnostRoditelja { get; set; }
        public string Fotografija { get; set; }
        public int Expr27 { get; set; }
        public string Expr28 { get; set; }
        public string Expr24 { get; set; }
        public string Expr29 { get; set; }
        public string Expr25 { get; set; }
        public int Expr26 { get; set; }
        public string Expr30 { get; set; }
        public string Expr31 { get; set; }
        public int ProduzetekPasosaID { get; set; }
        public string LicnaKarta { get; set; }
        public string StariPasos { get; set; }
        public string TroskoviUplate { get; set; }
        public string Expr32 { get; set; }
        public int KorsinikID { get; set; }
        public string Lozinka { get; set; }
        public int Pasos { get; set; }
    }
}
